### ISSUE TITLE
Support for array syntax in Merge/Unpack

### ISSUE THREAD

**Issue by urso** [urso/ucfg#12]
Proposal: Treat arrays like objects, with numeric keys only. Syntax based on separate path elements (e.g. by `.`):  `path.to.array.0`

By treating arrays and maps similarly these yaml like configurations will be treated as equivalent:

```
object:
  sub1:
    0: 
      title: "test0"
    1: 
      title: "test1"
    2:
      title: "test2"
```
or

```
object:
  sub1:
    - title: "test0"
    - title: "test1"
    - title: "test2"
```

or

```
object.sub1:
  - title: "test0"
  - title: "test1"
  - title: "test2"
```

or 

```
object.sub1.0.title: "test0"
object.sub1.1.title: "test1"
object.sub1.2.title: "test2"
```
